### ISSUE TITLE
Online / Server available

### ISSUE THREAD

**Issue by Solido** [matanlurey/cynic#1]
I'd like to use multiple instances because I'm very cynic :)

- Am I online
- Federation server online
- App server online

Can we make cynic with optional parameter for the server ?

Thx !

**Comment by matanlurey** [comment]
Sure! Let me just get a better idea of what you want, I imagine something like?

```dart
Future<bool> isOnline([String hostOrIp]);
```

Generally speaking you won't want to ping your own server too much :)

**Comment by Solido** [comment]
Right this is Cynic not [Loic](https://en.wikipedia.org/wiki/Low_Orbit_Ion_Cannon) ;)

How I may use  it

```dart
Cynic.register({
   'federation':'256.257.258.999',
   'api':'256.257.258.1',
   'oauth':'256.257.258.x'});

Cynic.isOnline('federation').then({}).orElse({});

Cynic.allOnline()

```

**Comment by matanlurey** [comment]
@Solido: Hmm. I could see this being useful for others. How about the following API:

```dart
/// Returns a stream of online statuses from [ipsOrHosts].
Stream<bool> allOnline(Iterable<String> ipsOrHosts);
```

and/or

```dart
abstract class Status {
  static Future<bool> allOnline(Iterable<Status> statuses) => ...

  const factory Status.host(String hostName, [String name]);
  const factory Status.http(String url, [String name]);
  const factory Status.ip(String ipAddress, [String name]);

  Future<bool> get isOnline;
}
```

## Example use

```dart
allOnline([
  '256.257.258.999',
  '256.257.258.1',
]);
```

and/or

```dart
final servers = const [
  const Status.ip('256.257.258.999', 'Federation'),
  const Status.ip('256.257.258.1', 'API'),
  const Status.ip('256.257.258.2', 'OAuth'),
];

print(await Status.allOnline(servers));
```

**Comment by Solido** [comment]
Thinking about a concrete Flutter case, register all micro services and online should responds under a period of time or display a message. Maybe it can help define the features we need ?

// Pure code API
```dart
final servers = const [
  const Status.ip('256.257.258.999', 'Federation'),
  const Status.ip('256.257.258.1', 'API'),
  const Status.ip('256.257.258.2', 'OAuth'),
];

Status.allOnline(servers, duration : 3000)).then( [valid infos server/time] => {
// setState() render the home
// eventual perf analytics
}).orElse([invalid server/time] => {
// display error
// crash analytics
});

```

Implementing an expressive Flutter widget relying on the API.
```dart
OnlineStatusWidgetBuilder([servers], {duration:2000}
waiting : LoadingWidget,
offline : WidgetBuilder( [offline servers details] => { 
// Build a view with messages and retry
})
online: Widget // It works
)
```

**Comment by matanlurey** [comment]
> Thinking about a concrete Flutter case, register all micro services and online should responds under a period of time or display a message. Maybe it can help define the features we need ?
> 
> // Pure code API
> ```dart
> final servers = const [
>   const Status.ip('256.257.258.999', 'Federation'),
>   const Status.ip('256.257.258.1', 'API'),
>   const Status.ip('256.257.258.2', 'OAuth'),
> ];
> 
> Status.allOnline(servers, duration : 3000)).then( [valid infos server/time] => {
> // setState() render the home
> // eventual perf analytics
> }).orElse([invalid server/time] => {
> // display error
> // crash analytics
> });

Wouldn't this potentially drain the battery? I'm still learning about best Flutter practices.

> 
> ```
> 
> Implementing an expressive Flutter widget relying on the API.
> ```dart
> OnlineStatusWidgetBuilder([servers], {duration:2000}
> waiting : LoadingWidget,
> offline : WidgetBuilder( [offline servers details] => { 
> // Build a view with messages and retry
> })
> online: Widget // It works
> )
> ```

I like this idea!

@Solido Do you want to take a shot at sending a PR? Happy to review.

**Comment by Solido** [comment]
Duration is a timeout ! it's only one call. All servers should respond before the period.

I'm still fighting really hard to get Firebase/Google Sign in to works but this is on my planning.

**Comment by matanlurey** [comment]
No worries. Let me send you something then, maybe you can review?

**Comment by Solido** [comment]
Yep ! let's go on this
